# Generated by Django 5.2.9 on 2025-12-09 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('MR', 'Medical Representative')], default='MR', max_length=10),
        ),
    ]
