# Generated by Django 5.2.9 on 2025-12-10 01:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visits', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AssignedVisit',
        ),
    ]
