# Generated by Django 5.2.9 on 2025-12-13 07:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visits', '0002_delete_assignedvisit'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorvisit',
            name='visit_type',
            field=models.CharField(choices=[('self', 'Self Visit'), ('task', 'Task-Based Visit')], default='self', max_length=10),
        ),
        migrations.AddField(
            model_name='shopvisit',
            name='visit_type',
            field=models.CharField(choices=[('self', 'Self Visit'), ('task', 'Task-Based Visit')], default='self', max_length=10),
        ),
        migrations.AddIndex(
            model_name='doctorvisit',
            index=models.Index(fields=['mr', '-visit_date'], name='visits_doct_mr_id_36a7f0_idx'),
        ),
        migrations.AddIndex(
            model_name='doctorvisit',
            index=models.Index(fields=['visit_date', '-visit_time'], name='visits_doct_visit_d_3ffb1a_idx'),
        ),
        migrations.AddIndex(
            model_name='shopvisit',
            index=models.Index(fields=['mr', '-visit_date'], name='visits_shop_mr_id_38f99c_idx'),
        ),
        migrations.AddIndex(
            model_name='shopvisit',
            index=models.Index(fields=['visit_date', '-visit_time'], name='visits_shop_visit_d_608ae0_idx'),
        ),
    ]
